### ISSUE TITLE
SystemJS failing loading when production mode

### ISSUE THREAD

**Issue by luruke** [redbullmediahouse/custom-script-vanilla-js#26]
Using this example, just changing the webpack config mode from `development` to `production` on L13 (https://github.com/redbullmediahouse/custom-script-vanilla-js/blob/master/webpack.config.js#L13) will cause the SystemJS failing loading the script with the following error:

![err](https://user-images.githubusercontent.com/61326/100737709-ce2bea80-33d4-11eb-9620-e3d505f6b299.png)

Is this a known issue?
Is there any known workaround?

**Comment by robertmaier** [comment]
Hey @luruke!
Thanks for reporting this issue. We have just merged a fix for it.
Best Regards,
Robert

**Comment by luruke** [comment]
Thank you @robertmaier ,  fix confirmed!
